export const productsList = [
  {
    uid: "kbrd_psre363",
    type: "کیبورد",
    category: "keyboard",
    title: "PSR_E363",
    rate: 4.3,
    price: 55000000,
    offPrice: 53000000,
    imageLgUrl: require("../images/Products/keyboard/PSR_E363_lg.jpg"),
    imageMdUrl: require("../images/Products/keyboard/PSR_E363_md.jpg"),
    imageSmUrl: require("../images/Products/keyboard/PSR_E363_sm.jpg"),
  },
  {
    uid: "kbrd_psre473",
    type: "کیبورد",
    category: "keyboard",
    title: "PSR_E473",
    rate: 4.4,
    price: 62000000,
    offPrice: 62000000,
    imageLgUrl: require("../images/Products/keyboard/PSR_E473_lg.jpg"),
    imageMdUrl: require("../images/Products/keyboard/PSR_E473_md.jpg"),
    imageSmUrl: require("../images/Products/keyboard/PSR_E473_sm.jpg"),
  },
  {
    uid: "kbrd_psrew425",
    type: "کیبورد",
    category: "keyboard",
    title: "PSR_EW425",
    rate: 4.4,
    price: 70000000,
    offPrice: 68000000,
    imageLgUrl: require("../images/Products/keyboard/PSR_EW425_lg.jpg"),
    imageMdUrl: require("../images/Products/keyboard/PSR_EW425_md.jpg"),
    imageSmUrl: require("../images/Products/keyboard/PSR_EW425_sm.jpg"),
  },
  {
    uid: "kbrd_psrf51",
    type: "کیبورد",
    category: "keyboard",
    title: "PSR_F51",
    rate: 4.4,
    price: 40000000,
    offPrice: 30000000,
    imageLgUrl: require("../images/Products/keyboard/PSR_F51_lg.jpg"),
    imageMdUrl: require("../images/Products/keyboard/PSR_F51_md.jpg"),
    imageSmUrl: require("../images/Products/keyboard/PSR_F51_sm.jpg"),
  },
  {
    uid: "kbrd_psrs950",
    type: "کیبورد",
    category: "keyboard",
    title: "PSR_S950",
    rate: 4.4,
    price: 80000000,
    offPrice: 72000000,
    imageLgUrl: require("../images/Products/keyboard/PSR_S950_lg.jpg"),
    imageMdUrl: require("../images/Products/keyboard/PSR_S950_md.jpg"),
    imageSmUrl: require("../images/Products/keyboard/PSR_S950_sm.jpg"),
  },
  {
    uid: "kbrd_psrs975",
    type: "کیبورد",
    category: "keyboard",
    title: "PSR_S975",
    rate: 4.4,
    price: 90000000,
    offPrice: 87200000,
    imageLgUrl: require("../images/Products/keyboard/PSR_S975_lg.jpg"),
    imageMdUrl: require("../images/Products/keyboard/PSR_S975_md.jpg"),
    imageSmUrl: require("../images/Products/keyboard/PSR_S975_sm.jpg"),
  },
  {
    uid: "kbrd_psre443",
    type: "کیبورد",
    category: "keyboard",
    title: "PSRE443",
    rate: 4.4,
    price: 42000000,
    offPrice: 39000000,
    imageLgUrl: require("../images/Products/keyboard/PSRE443_lg.jpg"),
    imageMdUrl: require("../images/Products/keyboard/PSRE443_md.jpg"),
    imageSmUrl: require("../images/Products/keyboard/PSRE443_sm.jpg"),
  },
  {
    uid: "pno_clp795gp",
    type: "پیانو",
    category: "piano",
    title: "CLP-795GP",
    rate: 4.3,
    price: 250000000,
    offPrice: 235000000,
    imageLgUrl: require("../images/Products/piano/CLP-795GPPE_th_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/CLP-795GPPE_th_md.jpg"),
    imageSmUrl: require("../images/Products/piano/CLP-795GPPE_th_sm.jpg"),
  },
  {
    uid: "pno_clp785",
    type: "پیانو",
    category: "piano",
    title: "CLP-785",
    rate: 4.1,
    price: 65000000,
    offPrice: 65000000,
    imageLgUrl: require("../images/Products/piano/CLP-785PE_th_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/CLP-785PE_th_md.jpg"),
    imageSmUrl: require("../images/Products/piano/CLP-785PE_th_sm.jpg"),
  },
  {
    uid: "pno_cvp701",
    type: "پیانو",
    category: "piano",
    title: "CVP-701",
    rate: 3.5,
    price: 79000000,
    offPrice: 76300000,
    imageLgUrl: require("../images/Products/piano/CVP-701_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/CVP-701_md.jpg"),
    imageSmUrl: require("../images/Products/piano/CVP-701_sm.jpg"),
  },
  {
    uid: "pno_cvp809",
    type: "پیانو",
    category: "piano",
    title: "CVP-809",
    rate: 3.9,
    price: 57000000,
    offPrice: 50000000,
    imageLgUrl: require("../images/Products/piano/CVP-809_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/CVP-809_md.jpg"),
    imageSmUrl: require("../images/Products/piano/CVP-809_sm.jpg"),
  },
  {
    uid: "pno_cvp809gp",
    type: "پیانو",
    category: "piano",
    title: "CVP-809GP",
    rate: 4.7,
    price: 108000000,
    offPrice: 918000000,
    imageLgUrl: require("../images/Products/piano/CVP-809GP_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/CVP-809GP_md.jpg"),
    imageSmUrl: require("../images/Products/piano/CVP-809GP_sm.jpg"),
  },
  {
    uid: "pno_dgx660",
    type: "پیانو",
    category: "piano",
    title: "DGX-660",
    rate: 4.9,
    price: 49500000,
    offPrice: 47500000,
    imageLgUrl: require("../images/Products/piano/DGX-660_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/DGX-660_md.jpg"),
    imageSmUrl: require("../images/Products/piano/DGX-660_sm.jpg"),
  },
  {
    uid: "pno_dgx670",
    type: "پیانو",
    category: "piano",
    title: "DGX-670",
    rate: 3,
    price: 44000000,
    offPrice: 41000000,
    imageLgUrl: require("../images/Products/piano/DGX-670_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/DGX-670_md.jpg"),
    imageSmUrl: require("../images/Products/piano/DGX-670_sm.jpg"),
  },
  {
    uid: "pno_dgx660",
    type: "پیانو",
    category: "piano",
    title: "GB1K-1",
    rate: 3.8,
    price: 61000000,
    offPrice: 61000000,
    imageLgUrl: require("../images/Products/piano/GB1K-1_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/GB1K-1_md.jpg"),
    imageSmUrl: require("../images/Products/piano/GB1K-1_sm.jpg"),
  },
  {
    uid: "pno_p515",
    type: "پیانو",
    category: "piano",
    title: "P-515",
    rate: 4.4,
    price: 39000000,
    offPrice: 38000000,
    imageLgUrl: require("../images/Products/piano/P-515_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/P-515_md.jpg"),
    imageSmUrl: require("../images/Products/piano/P-515_sm.jpg"),
  },
  {
    uid: "pno_ydp184",
    type: "پیانو",
    category: "piano",
    title: "YDP-184",
    rate: 4.2,
    price: 37000000,
    offPrice: 33500000,
    imageLgUrl: require("../images/Products/piano/YDP-184_lg.jpg"),
    imageMdUrl: require("../images/Products/piano/YDP-184_md.jpg"),
    imageSmUrl: require("../images/Products/piano/YDP-184_sm.jpg"),
  },
];
