export const productsList = [
  {
    category: "keyboard",
    title: "PSR_E363",
    rate: 4.3,
    price: 68000000,
    offPrice: 61500000,
    imageUrl: require("../images/Products/keyboard/PSR_E363.jpg"),
  },
  {
    category: "keyboard",
    title: "PSR_E473",
    rate: 4.4,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/keyboard/PSR_E473.jpg"),
  },
  {
    category: "keyboard",
    title: "PSR_EW425",
    rate: 4.4,
    price: 70000000,
    offPrice: 0,
    imageUrl: require("../images/Products/keyboard/PSR_EW425.jpg"),
  },
  {
    category: "keyboard",
    title: "PSR_F51",
    rate: 4.4,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/keyboard/PSR_F51.jpg"),
  },
  {
    category: "keyboard",
    title: "PSR_S950",
    rate: 4.4,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/keyboard/PSR_S950.jpg"),
  },
  {
    category: "keyboard",
    title: "PSR_S975",
    rate: 4.4,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/keyboard/PSR_S975.jpg"),
  },
  {
    category: "keyboard",
    title: "PSRE443",
    rate: 4.4,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/keyboard/PSRE443.jpg"),
  },
  {
    category: "piano",
    title: "CLP-795GP",
    rate: 4.3,
    price: 68000000,
    offPrice: 61500000,
    imageUrl: require("../images/Products/piano/CLP-795GPPE_th.jpg"),
  },
  {
    category: "piano",
    title: "CLP-785",
    rate: 4.1,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/CLP-785PE_th.jpg"),
  },
  {
    category: "piano",
    title: "CVP-701",
    rate: 3.5,
    price: 70000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/CVP-701.jpg"),
  },
  {
    category: "piano",
    title: "CVP-809",
    rate: 3.9,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/CVP-809.jpg"),
  },
  {
    category: "piano",
    title: "CVP-809GP",
    rate: 4.7,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/CVP-809GP.jpg"),
  },
  {
    category: "piano",
    title: "DGX-660",
    rate: 4.9,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/DGX-660.jpg"),
  },
  {
    category: "piano",
    title: "DGX-670",
    rate: 3,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/DGX-670.jpg"),
  },
  {
    category: "piano",
    title: "GB1K-1",
    rate: 3.8,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/GB1K-1.jpg"),
  },
  {
    category: "piano",
    title: "P-515",
    rate: 4.4,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/P-515.jpg"),
  },
  {
    category: "piano",
    title: "YDP-184",
    rate: 4.2,
    price: 72000000,
    offPrice: 0,
    imageUrl: require("../images/Products/piano/YDP-184.jpg"),
  },
];
